assets: /workspace/LIBERO/libero/libero/./assets
bddl_files: /workspace/LIBERO/libero/libero/./bddl_files
benchmark_root: /workspace/LIBERO/libero/libero
datasets: /workspace/LIBERO/libero/libero/../datasets
init_states: /workspace/LIBERO/libero/libero/./init_files
